project:
  type: website
  output-dir: docs

website:
  title: "Estatística Básica com R"
  site-path: /estatistica-basica-r
  navbar:
    left:
      - text: Início
        href: index.qmd
      - text: Aulas
        href: aulas/aulas.qmd
      - text: Exercícios
        href: exercicios.qmd
      - text: Materiais
        href: materiais.qmd
      - text: Envio 
        href: envio.qmd

format:
  html:
    theme: cosmo
    toc: true
    lang: pt-BR
